### ISSUE TITLE
[github-actions] - deploy on master branch

### ISSUE THREAD

**Issue by daniele-zurico** [jstacoder/jstacoder.github.io#2]
Hi @jstacoder,
I'm following your post on:
https://jstacoder.github.io/blog/2019-09-17-gatsby-deployment-with-github-actions/

This is my config file:
https://github.com/daniele-zurico/daniele-zurico.github.com/blob/develop/.github/workflows/main.yml

But instead to deploy on `master` it's deploying on `gh-pages`:
https://github.com/daniele-zurico/daniele-zurico.github.com/commit/0db21b3036536a6fdfc462f700e7dd557d8f32cd/checks?check_suite_id=288560064

Can you please tell me if I'm doing something wrong?

Thanks,
Daniele

**Comment by jstacoder** [comment]
so that action maxheld83/ghpages does not give the option to customize the branch, it either pushs to master on your users `github pages` repo ie:  your repo named `GITHUB_USERNAME.github.io` or to the `gh-pages` branch otherwise, which is usually what you want, if you didnt you could just call the `gh-pages` command yourself, but since it will push to master if you are using your user github.io repo, but it looks like the repo you are using is called: `daniele-zurico.github.com` if you create a repo instead called: `aniele-zurico.github.io` it will push to the master branch for you
